rules:
  indent:
    - 0
    - 4
  quotes:
    - 0
    - double
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - always
env:
  es6: true
  node: true
  browser: false
extends: 'eslint:recommended'
ecmaFeatures:
  modules: true
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
